# Generated by Django 5.2.7 on 2025-11-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': False},
        ),
    ]
