# Generated by Django 5.2.7 on 2025-11-19 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_column='for_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.fornecedor'),
        ),
    ]
