# Generated by Django 5.2.7 on 2025-11-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_documentofornecedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoFornecedor',
        ),
    ]
