# Generated by Django 5.2.7 on 2025-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ui_permissoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
