# Generated by Django 5.2.7 on 2025-11-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('fornecedores', '0002_alter_fornecedor_options'),
        ('produtos', '0002_movimentacaoestoque'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
            options={
                'db_table': 'tb_relatorio_vendas',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
