# Generated by Django 5.2.7 on 2025-11-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatorioVendas',
        ),
    ]
