# Generated by Django 5.2.7 on 2025-11-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_options'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS tb_clientes (
                id INT AUTO_INCREMENT PRIMARY KEY,
                nome VARCHAR(100) NOT NULL,
                rg VARCHAR(30),
                cpf VARCHAR(20),
                email VARCHAR(200),
                telefone VARCHAR(30),
                celular VARCHAR(30),
                cep VARCHAR(100),
                endereco VARCHAR(255),
                numero INT,
                complemento VARCHAR(200),
                bairro VARCHAR(100),
                cidade VARCHAR(100),
                estado VARCHAR(2)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS tb_clientes;"
        ),
    ]
