# Generated by Django 5.2.7 on 2025-11-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fornecedor',
            table='tb_fornecedores',
        ),
    ]
