# Generated by Django 5.2.7 on 2025-10-27 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0002_movimentacaoestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(db_column='cli_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='clientes.cliente')),
                ('funcionario', models.ForeignKey(db_column='fun_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_vendas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto')),
                ('venda', models.ForeignKey(db_column='ven_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'db_table': 'tb_itens_venda',
                'managed': True,
            },
        ),
    ]
