# Generated by Django 5.2.7 on 2025-11-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_delete_documentofornecedor'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(db_column='pro_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='produtos.produto'),
        ),
    ]
